-- 코드를 입력하세요
# 테이블  SUV 인 자동차
# SELECT CAR_TYPE ='SUV' 
# 소수 첫번째 자리에서 반올림 
# SELECT ROUND(AVG(DAILY_FEE),1) AS AVERAGE_FEE
SELECT ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
# 평균 일일 대여 요금
#  별칭 AS
# AVERAGE_FEE = AVG(DAILY_FEE);
# AVERAGE_FEE As AVG(DAILY_FEE)
WHERE CAR_TYPE ='SUV';